### ISSUE TITLE
In production env: can't convert nil into Integer

### ISSUE THREAD

**Issue by drnic** [mattetti/wd-sinatra#13]
Under puma and thin (the two I tested), running in production environment, I am getting the error "can't convert nil into Integer" on requests.

```
2012-05-16 19:41:36 -0700: Rack app error: #<TypeError: can't convert nil into Integer>
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:896:in `Integer'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:896:in `handle_exception!'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:888:in `rescue in dispatch!'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:891:in `dispatch!'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:719:in `block in call!'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `block in invoke'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `catch'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `invoke'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:719:in `call!'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:705:in `call'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.4.1/lib/rack/content_length.rb:14:in `call'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17:in `call'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.4.1/lib/rack/logger.rb:15:in `call'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.4.1/lib/rack/commonlogger.rb:20:in `call'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.4.1/lib/rack/head.rb:9:in `call'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in `call'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:1334:in `block in call'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:1416:in `synchronize'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:1334:in `call'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.4.1/lib/rack/commonlogger.rb:20:in `call'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/puma-1.3.0/lib/puma/server.rb:418:in `handle_request'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/puma-1.3.0/lib/puma/server.rb:288:in `process_client'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/puma-1.3.0/lib/puma/server.rb:197:in `block in run'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/puma-1.3.0/lib/puma/thread_pool.rb:92:in `call'
/Users/drnic/.rvm/gems/ruby-1.9.3-p194@global/gems/puma-1.3.0/lib/puma/thread_pool.rb:92:in `block in spawn_thread'
```

The service returns a basic json output that works in dev mode.

Is this a wd-sinatra issue or a Sinatra issue?

**Comment by mattetti** [comment]
Can you repo with a freshly generated app? It looks like the content length
middleware is having issue, which is more than likely not due to WD, but I
can't say for sure without reproducing the issue.

On Thu, May 17, 2012 at 4:45 AM, Dr Nic Williams <
reply@reply.github.com

**Comment by drnic** [comment]
Good idea. I'll do that soon.

**Comment by fbjork** [comment]
I'm also seeing this at random in a Sinatra app using Unicorn. Any solution for it?

**Comment by mattetti** [comment]
I'm not sure what triggers this error since I haven't seen it in prod yet. I did see that one tho: https://github.com/rack/rack/pull/378 which is slightly different.
