### ISSUE TITLE
Having trouble with new relic

### ISSUE THREAD

**Issue by dsshap** [mattetti/wd-sinatra#38]
I am getting this error when I add wd_new_relic_rpm and uncommented 

require 'newrelic_instrumentation' 

in hooks.rb

Error below,

/lib/newrelic_instrumentation.rb:22:in `block (3 levels) in <top (required)>': undefined method`add_method_tracer' for WeaselDiesel::RequestHandler:Class (NoMethodError)

I am using,
wd_newrelic_rpm (3.5.8)
wd_sinatra (2.0.0)
weasel_diesel (1.3.0)

**Comment by mattetti** [comment]
can you make sure you are using rpm 3.5.8

**Comment by dsshap** [comment]
I wasn't before, but now i am at,

newrelic_rpm (3.5.8.72)

And I am still getting the same issue

``` ruby

13:36:36 web.1  | /Users/dave/Documents/scout/workspace/hardware_gateway/lib/newrelic_instrumentation.rb:22:in `block (3 levels) in <top (required)>': undefined method `add_method_tracer' for WeaselDiesel::RequestHandler:Class (NoMethodError)
13:36:36 web.1  |   from /Users/dave/Documents/scout/workspace/hardware_gateway/lib/newrelic_instrumentation.rb:14:in `class_eval'
13:36:36 web.1  |   from /Users/dave/Documents/scout/workspace/hardware_gateway/lib/newrelic_instrumentation.rb:14:in `block (2 levels) in <top (required)>'
13:36:36 web.1  |   from /Users/dave/.rvm/gems/ruby-2.0.0-p247@scout_hardware_gateway/gems/wd_newrelic_rpm-3.5.8/vendor/gems/dependency_detection-0.0.1.build/lib/dependency_detection.rb:49:in `call'
13:36:36 web.1  |   from /Users/dave/.rvm/gems/ruby-2.0.0-p247@scout_hardware_gateway/gems/wd_newrelic_rpm-3.5.8/vendor/gems/dependency_detection-0.0.1.build/lib/dependency_detection.rb:49:in `block in execute'
13:36:36 web.1  |   from /Users/dave/.rvm/gems/ruby-2.0.0-p247@scout_hardware_gateway/gems/wd_newrelic_rpm-3.5.8/vendor/gems/dependency_detection-0.0.1.build/lib/dependency_detection.rb:48:in `each'
13:36:36 web.1  |   from /Users/dave/.rvm/gems/ruby-2.0.0-p247@scout_hardware_gateway/gems/wd_newrelic_rpm-3.5.8/vendor/gems/dependency_detection-0.0.1.build/lib/dependency_detection.rb:48:in `execute'
13:36:36 web.1  |   from /Users/dave/.rvm/gems/ruby-2.0.0-p247@scout_hardware_gateway/gems/wd_newrelic_rpm-3.5.8/vendor/gems/dependency_detection-0.0.1.build/lib/dependency_detection.rb:15:in `block in detect!'
13:36:36 web.1  |   from /Users/dave/.rvm/gems/ruby-2.0.0-p247@scout_hardware_gateway/gems/wd_newrelic_rpm-3.5.8/vendor/gems/dependency_detection-0.0.1.build/lib/dependency_detection.rb:13:in `each'
13:36:36 web.1  |   from /Users/dave/.rvm/gems/ruby-2.0.0-p247@scout_hardware_gateway/gems/wd_newrelic_rpm-3.5.8/vendor/gems/dependency_detection-0.0.1.build/lib/dependency_detection.rb:13:in `detect!'
13:36:36 web.1  |   from /Users/dave/Documents/scout/workspace/hardware_gateway/lib/newrelic_instrumentation.rb:67:in `<top (required)>'
13:36:36 web.1  |   from /Users/dave/Documents/scout/workspace/hardware_gateway/lib/hooks.rb:101:in `require'
```
